sudo: false
language: node_js
node_js:
    - "12"
install:
    - npm ci
script:
    - set -eo pipefail
    - node -v
    - npm run lint
    - npm run test
    - npm run build
    - npm run publish-ci
